require './lib/components/player'
require './lib/components/property'
require './lib/components/improvement'
require './lib/components/house_and_hotel'
require './lib/actions/property_improvement'
require './lib/actions/monopoly_check'
require './lib/errors/too_many_improvements'
require './lib/errors/incorrect_set_error'